channels:
- conda-forge
dependencies:
- python=3.11.10
- pip<=23.3.1
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - numpy==2.4.1
  - pandas==2.2.3
  - psutil==7.2.1
  - pyarrow==17.0.0
  - scikit-learn==1.7.2
  - scipy==1.17.0
name: mlflow-env
